spring.aplication.name=GestionResiduosBackend

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Security configuration
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=7200000
security.jwt.refresh-token.expiration=86400000

# Logging configuration
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

# Swagger configuration

# Disable Spring Boot Docker Compose integration when no docker-compose.yml is present
spring.docker.compose.enabled=false

server.port=8080

# Logging configuration for file output
logging.file.name=logs/application.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

# Email configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

